version: 1.0.{build}
branches:
  only:
  - master
image: Visual Studio 2017
configuration: Release
environment:
  git_access_token:
    secure: 63d6fd6bde1fd5643f41df9324fb2a8a174b5468 
  matrix:
    - framework: netcoreapp2.0
before_build:
- ps: >-
    dotnet restore .\lib\PuppeteerSharp.sln

    New-SelfSignedCertificate -Subject "localhost" -FriendlyName "Puppeteer" -CertStoreLocation "cert:\CurrentUser\My"

    Get-ChildItem -Path cert:\CurrentUSer\my | where { $_.friendlyname -eq "Puppeteer" } | Export-Certificate -FilePath C:\projects\docfx-playground\lib\PuppeteerSharp.TestServer\testCert.cer

build:
  project: .\lib\PuppeteerSharp.sln
  publish_nuget: true
  include_nuget_references: true
  verbosity: minimal
install:
- ps: >-
    if($env:APPVEYOR_REPO_TAG -eq 'True') {
    
        choco install docfx

    }
after_build:
- ps: AppVeyor/GenerateDocs.ps1